In [2]:
# question 1
import numpy as np
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# question 2
print(np.ones((3, 3)) > 0)
print(np.ones((3, 3), dtype=bool))
print(np.full((3, 3), fill_value=True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# question 3
import numpy as np
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [6]:
# question 4
import numpy as np
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
# question 5
import numpy as np
arr = np.arange(0, 10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# question 6
import numpy as np
arr = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate((arr, arr2), axis=0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
# question 7
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate((arr1, arr2), axis=1)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [12]:
# question 8
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [13]:
# question 9
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print("result", a[index])

result [ 6  9 10]


In [14]:
# question 10
import numpy as np

def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx,otypes=[float])

print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [15]:
# question 11
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a < b, b, a))

Result [6 7 9 8 9 7 5]


In [16]:
# question 12
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 33.8MB/s]


In [25]:
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img, axis=-1) + np.min(img, axis=-1)) / 2
print(gray_img_01[0, 0])

102.5


In [34]:
# question 13
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
gray_img_02 = np.sum(img, axis=-1) / 3
print(gray_img_02[0, 0])

107.66666666666667


In [35]:
# question 14
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
gray_img_03 = np.dot(img, [0.21, 0.72, 0.07])
print(gray_img_03[0, 0])

126.22999999999999


In [37]:
# question 15
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 10.7MB/s]


In [39]:
import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()

In [50]:
sales = data[:, 3]
max = np.max(sales)
index = np.argmax(sales)
print(f'Max: {max} - Index: {index}')

Max: 27.0 - Index: 175


In [51]:
# question 16
tv = data[:, 0]
print(np.mean(tv))

147.0425


In [53]:
# question 17
print(np.count_nonzero(sales >= 20))
print(np.sum(np.where(sales >= 20, 1, 0)))

40
40


In [56]:
# question 18
radio = data[:, 1]
print(np.mean(radio, where=sales >= 15))

26.22293577981651


In [57]:
# question 19
newspaper = data[:, 2]
mean_newspaper = np.mean(newspaper)
print(np.sum(sales, where=newspaper > mean_newspaper))

1405.1000000000006


In [61]:
# question 20
mean_sales = np.mean(sales)
scores = sales[:]
scores = np.where(scores > mean_sales, 'Good', np.where(scores < mean_sales, 'Bad', 'Average'))
print(scores[7:10])

['Bad' 'Bad' 'Good']


In [73]:
# question 21
nearest_mean_sales_idx = np.argmin(np.abs(sales - mean_sales))
sales[nearest_mean_sales_idx]
scores = sales[:]
scores = np.where(scores > sales[nearest_mean_sales_idx], 'Good', np.where(scores < sales[nearest_mean_sales_idx], 'Bad', 'Average'))
print(scores[7:10])

['Bad' 'Bad' 'Good']
