<a href="https://colab.research.google.com/github/builamquangngoc91/AIO-HW/blob/main/M1W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Example 1
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
data

tensor([1., 2., 3.])

In [2]:
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [3]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total

my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [111]:
data = torch.Tensor([1, 2, 30000000])
data

In [5]:
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0., 0., nan])

In [16]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c = torch.max(x, dim=0)
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total

stable_softmax = StableSoftmax()
output = stable_softmax(data)
output

tensor([0., 0., 1.])

In [77]:
# example 2:

from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass

    def get_yob(self):
        return self._yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name=name, yob=yob)
        self.__grade = grade

    def describe(self):
        print(f"Student - Name: {self._name}, YoB: {self._yob}, Grade: {self.__grade}")

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name=name, yob=yob)
        self.__specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self._name}, YoB: {self._yob}, Specialist: {self.__specialist}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name=name, yob=yob)
        self.__subject = subject

    def describe(self):
        print(f"Teacher - Name: {self._name}, YoB: {self._yob}, Specialist: {self.__subject}")

In [78]:
student1 = Student(name="John", yob=2000, grade="A")
student1.describe()

Student - Name: John, YoB: 2000, Grade: A


In [79]:
doctor1 = Doctor(name="John", yob=2000, specialist="Neurology")
doctor1.describe()

Doctor - Name: John, YoB: 2000, Specialist: Neurology


In [80]:
teacher1 = Teacher(name="John", yob=2000, subject="Mathematics")
teacher1.describe()

Teacher - Name: John, YoB: 2000, Specialist: Mathematics


In [87]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__list_people = list()

    def add_person(self, person: Person):
        self.__list_people.append(person)

    def describe(self):
        print(f"Name: {self.__name}")
        for p in self.__list_people:
            p.describe()

    def count_doctor(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter

    def sort_yob(self):
        self.__list_people.sort(key=lambda x: x.get_yob(), reverse=True)

    def compute_average(self):
        total = 0
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Teacher):
              total += p.get_yob()
              counter += 1
        return total / counter

In [88]:
ward1 = Ward("Ward1")
ward1.add_person(student1)
ward1.add_person(doctor1)
ward1.describe()

Name: Ward1
Student - Name: John, YoB: 2000, Grade: A
Doctor - Name: John, YoB: 2000, Specialist: Neurology


In [89]:
ward1.count_doctor()

1

In [90]:
ward1.sort_yob()

In [91]:
ward1.describe()

Name: Ward1
Student - Name: John, YoB: 2000, Grade: A
Doctor - Name: John, YoB: 2000, Specialist: Neurology


In [92]:
ward1.compute_average()

0.0

In [96]:
# Example 3

class MyStack:
  def __init__(self, capacity):
    self.capacity = capacity
    self.__stack = []

  def is_empty(self):
    return len(self.__stack) == 0

  def is_full(self):
    return len(self.__stack) == self.capacity

  def push(self, value):
    if self.is_full():
      raise Exception('Overflow')
    self.__stack.append(value)

  def pop(self):
    if self.is_empty():
      raise Exception('Underflow')
    self.__stack.pop()

  def top(self):
    if self.is_empty():
      raise Exception('Underflow')
    return self.__stack[-1]

  def size(self):
    return len(self.__stack)


In [100]:
my_stack = MyStack(4)
print(my_stack.is_empty())
my_stack.push(5)
print(my_stack.is_empty())
print(my_stack.top())
print(my_stack.is_full())
print(my_stack.pop())
print(my_stack.is_empty())

True
False
5
False
None
True


In [101]:
# Example 4

class MyQueue:
  def __init__(self, capacity):
    self.capacity = capacity
    self.__queue = []

  def is_empty(self):
    return len(self.__queue) == 0

  def is_full(self):
    return len(self.__queue) == self.capacity

  def enqueue(self, value):
    if self.is_full():
      raise Exception('Overflow')
    self.__queue.append(value)

  def dequeue(self):
    if self.is_empty():
      raise Exception('Underflow')
    self.__queue.pop(0)

  def front(self):
    if self.is_empty():
      raise Exception('Queue is empty')
    return self.__queue[0]

  def size(self):
    return len(self.__queue)

In [107]:
my_queue = MyQueue(5)
print(my_queue.is_empty())
print(my_queue.is_full())
print(my_queue.enqueue(5))
print(my_queue.enqueue(4))
print(my_queue.enqueue(4))
print(my_queue.enqueue(5))
print(my_queue.front())
print(my_queue.is_empty())
print(my_queue.is_full())


True
False
None
None
None
None
5
False
False


In [108]:
# question 1
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [109]:
# question 2

import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        ### Your Code Here ###
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
        ### End Code Here ###

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [110]:
# question 3
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        ### Your Code Here ###
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
        ### End Code Here ###

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

In [112]:
# question 4

import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [115]:
# question 5

from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        return f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.grade}"

student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
print(student1.describe())

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


In [117]:
# question 6

from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        return f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.subject}"

teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
print(teacher1.describe())

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


In [118]:
# question 7

from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        return f"Doctor - Name: {self._name}, YoB: {self._yob}, Specialist: {self.specialist}"

doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endocrinologists")
assert doctor1._yob == 1981
print(doctor1.describe())

Doctor - Name: doctorZ2023, YoB: 1981, Specialist: Endocrinologists


In [120]:
# question 8

class Ward:
    def __init__(self, name: str):
        self._name = name
        self._listPeople = list()

    def add_person(self, person: Person):
        self._listPeople.append(person)

    def describe(self):
        print(f"Ward Name: {self._name}")
        for p in self._listPeople:
            p.describe()

    def count_doctor(self):
        count = 0
        for p in self._listPeople:
            if isinstance(p, Doctor):
                count += 1
        return count

student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
print(ward1.count_doctor())

2


In [121]:
# question 9

class MyStack:
    def __init__(self, capacity):
        self._capacity = capacity
        self._stack = []

    def is_full(self):
        return len(self._stack) == self._capacity

    def push(self, value):
        if not self.is_full():
            self._stack.append(value)
        else:
            raise Exception("Stack is full")

stack1 = MyStack(capacity=5)
stack1.push(1)

assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


In [122]:
# question 10

class MyStack:
    def __init__(self, capacity):
        self._capacity = capacity
        self._stack = []

    def is_full(self):
        return len(self._stack) == self._capacity

    def push(self, value):
        if not self.is_full():
            self._stack.append(value)
        else:
            raise Exception("Stack is full")

    def top(self):
        if self._stack:
            return self._stack[-1]
        else:
            raise Exception("Stack is empty")

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


In [123]:
# question 11

class MyQueue:
    def __init__(self, capacity):
        self._capacity = capacity
        self._queue = []

    def is_full(self):
        return len(self._queue) == self._capacity

    def enqueue(self, value):
        if not self.is_full():
            self._queue.append(value)
        else:
            raise Exception("Queue is full")

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


In [124]:
# question 12

class MyQueue:
    def __init__(self, capacity):
        self._capacity = capacity
        self._queue = []

    def isEmpty(self):
        return len(self._queue) == 0

    def is_full(self):
        return len(self._queue) == self._capacity

    def dequeue(self):
        if not self.isEmpty():
            return self._queue.pop(0)
        else:
            raise Exception("Queue is empty")

    def enqueue(self, value):
        if not self.is_full():
            self._queue.append(value)
        else:
            raise Exception("Queue is full")

    def front(self):
        if not self.isEmpty():
            return self._queue[0]
        else:
            raise Exception("Queue is empty")

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())

1
